webtalk_init -webtalk_dir C:\\Users\\Administrator\\Desktop\\lab1\\lab1.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "星期一 三月 30 21:04:26 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "k0dduv68vo88mjbkso9f1cui1c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.4_1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1427714938123" -context "sdk\\\\hardware/1427714938123"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1427714938123"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1427714938123"
webtalk_add_data -client sdk -key VivadoVersion -value "2014.4" -context "sdk\\\\hardware/1427714938123"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1427714938123"
webtalk_add_data -client sdk -key Device -value "7z010" -context "sdk\\\\hardware/1427714938123"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1427714938123"
webtalk_add_data -client sdk -key uid -value "1427715107636" -context "sdk\\\\bsp/1427715107636"
webtalk_add_data -client sdk -key hwid -value "1427714938123" -context "sdk\\\\bsp/1427715107636"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1427715107636"
webtalk_add_data -client sdk -key apptemplate -value "memory_tests" -context "sdk\\\\bsp/1427715107636"
webtalk_add_data -client sdk -key uid -value "1427715117461" -context "sdk\\\\application/1427715117461"
webtalk_add_data -client sdk -key hwid -value "1427714938123" -context "sdk\\\\application/1427715117461"
webtalk_add_data -client sdk -key bspid -value "1427715107636" -context "sdk\\\\application/1427715117461"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1427715117461"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1427715117461"
webtalk_add_data -client sdk -key apptemplate -value "memory_tests" -context "sdk\\\\application/1427715117461"
webtalk_transmit -clientid 774559753 -regid "" -xml C:\\Users\\Administrator\\Desktop\\lab1\\lab1.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\Administrator\\Desktop\\lab1\\lab1.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\Administrator\\Desktop\\lab1\\lab1.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
